[package]
name = "bootstrap"
version = "0.1.0"
edition = "2021"

[dependencies]
futures    = "0.3.15"
structopt  = "0.3"
tokio         = { version = "1.7",  features = [ "macros", "io-util", "time", "process", "sync", "signal", "rt-multi-thread"] }
url        = "*"
