[package]
name = "bootstrap"
version = "0.9.0"
edition = "2021"

[dependencies]
    structopt  = "0.3"
    url        = "*"
    rustls     = "*"
    native-tls = "*"
    rustls-pki-types = "*"
    dns-lookup = "1.0.8"
    ureq       = { version = "3.0", features = ["rustls"], path="/ssw/projects/trentonio/ureq" }
    http       = { version = "1.3.0", path="/ssw/projects/pandora/UPSTREAM/rust-http/worktrees/add_dnsname_authority" }
    minerva-voucher = { path = "/ssw/projects/trentonio/minerva-voucher" }
    rand            = "0.4"
    # zeroize = "1.3.0"
    tracing-subscriber = { version = "*", features = ["env-filter"] }

[dev-dependencies]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(_YES_)'] }

[patch.crates-io]
    http = { path="/ssw/projects/pandora/UPSTREAM/rust-http/worktrees/add_dnsname_authority" }

#
# Local Variables:
# mode: rust
# compile-command: "cargo build"
# End:


